### Get all staff
GET http://localhost:3504/staff

### Get special staff
GET http://localhost:3504/staff/6168f26fd007c31d28b1c8a8
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MTY4ZjI2ZmQwMDdjMzFkMjhiMWM4YTgiLCJpYXQiOjE2MzQzNTE5NjYsImV4cCI6MTYzNDM1Mzc2Nn0.MRbTVCHuYv0SxTriuzQPXajcxGpY8mKY7ZGWHoa03BE


### Get profile current staff
GET http://localhost:3504/staff/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MTY4ZjI2ZmQwMDdjMzFkMjhiMWM4YTgiLCJpYXQiOjE2MzQ3OTk4MjUsImV4cCI6MTYzNDgwMTYyNX0.1Zhb9m72CNHa35r6i8EvngowOJxCfDkGj-6T4U8PyFg

### Login
POST http://localhost:3504/staff/login
content-type: application/json

{
    "email" : "example@example.com",
    "password" : "Xhung123"
}

### Logout
POST http://localhost:3504/staff/logout
content-type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MTY4ZjI2ZmQwMDdjMzFkMjhiMWM4YTgiLCJpYXQiOjE2MzQzNTE5NDgsImV4cCI6MTYzNDk1Njc0OH0.a5SvBSGub3Gsrbt2_jgQ7shxT6EgiLFlank3P5Alk_w"
}

### Register
POST http://localhost:3504/staff/register
content-type: application/json

{
    "name" : "test",
    "email" : "example@example.com",
    "password" : "Xhung123",
    "role" : "61659bff2293535ee4fcaf21"
}

### get_new_access_token
POST http://localhost:3504/staff/refresh-acess-token
content-type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MTY4ZjI2ZmQwMDdjMzFkMjhiMWM4YTgiLCJpYXQiOjE2MzQ3OTk3NDYsImV4cCI6MTYzNTQwNDU0Nn0.9NjBN-g_2IWTih_aYiUWRaAxFNxCuIduUAt6-kkAeDM"
}


### Add new role
POST  http://localhost:3504/role
content-type: application/json

{
    "name":"Manager",
    "color":"F56F6F"
}

# {
#     "name":"Seller",
#     "color":"F5EF55"
# }

# {
#     "name":"Accountant",
#     "color":"55F565"
# }

# {
#     "name":"Warehouse",
#     "color":"4B92FD"
# }

### Get all role
GET http://localhost:3504/role