### Get all staff
GET http://localhost:3504/staff

### Get special staff
GET http://localhost:3504/staff/6168f26fd007c31d28b1c8a8
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MTY4ZjI2ZmQwMDdjMzFkMjhiMWM4YTgiLCJpYXQiOjE2MzQzMTYxOTksImV4cCI6MTYzNDMxNzk5OX0.cjnO_PdH49TyAvVqBJV6G4WXxqF64rCaCnzh2pOStsU

### Login
POST http://localhost:3504/staff/login
content-type: application/json

{
    "email" : "example@example.com",
    "password" : "Xhung123"
}

### Logout
POST http://localhost:3504/staff/logout
content-type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MTY4ZjI2ZmQwMDdjMzFkMjhiMWM4YTgiLCJpYXQiOjE2MzQzMTYxODQsImV4cCI6MTYzNDkyMDk4NH0.YHBdByhG-Dk3Zaf_2k-rgmGF6kt7uGB-Sm8vdcRunJM"
}

### Register
POST http://localhost:3504/staff/register
content-type: application/json

{
    "name" : "test",
    "email" : "example@example.com",
    "password" : "Xhung123",
    "role" : "61659bff2293535ee4fcaf21"
}

### get_new_access_token
POST http://localhost:3504/staff/token
content-type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MTY4ZjI2ZmQwMDdjMzFkMjhiMWM4YTgiLCJpYXQiOjE2MzQzMTYxODQsImV4cCI6MTYzNDkyMDk4NH0.YHBdByhG-Dk3Zaf_2k-rgmGF6kt7uGB-Sm8vdcRunJM"
}


### Add new role
POST  http://localhost:3504/role
content-type: application/json

{
    "name":"Manager",
    "color":"F56F6F"
}

# {
#     "name":"Seller",
#     "color":"F5EF55"
# }

# {
#     "name":"Accountant",
#     "color":"55F565"
# }

# {
#     "name":"Warehouse",
#     "color":"4B92FD"
# }

### Get all role
GET http://localhost:3504/role