### Get all staff
GET http://localhost:3504/staff

### Get special staff
GET http://localhost:3504/staff/6168f26fd007c31d28b1c8a8
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MTY4ZjI2ZmQwMDdjMzFkMjhiMWM4YTgiLCJpYXQiOjE2MzQzMTE5OTksImV4cCI6MTYzNDMxMzc5OX0.QT1xH5sEHXR-XLPItEyybv3wFqhRDRf1_y6pEueJkSs 

### Login
POST http://localhost:3504/staff/login
content-type: application/json

{
    "email" : "example@example.com",
    "password" : "Xhung123"
}

### Logout
POST http://localhost:3504/staff/logout
content-type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MTY4ZjI2ZmQwMDdjMzFkMjhiMWM4YTgiLCJpYXQiOjE2MzQzMDc5NDksImV4cCI6MTYzNDkxMjc0OX0.QVbllcd5YXliWA7JMjEBtUH8xxNEaY_W4hv4jReK2qk"
}

### Register
POST http://localhost:3504/staff/register
content-type: application/json

{
    "name" : "test",
    "email" : "example@example.com",
    "password" : "Xhung123",
    "role" : "61659bff2293535ee4fcaf21"
}

### get_new_access_token
POST http://localhost:3504/staff/get_new_access_token
content-type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MTY4ZjI2ZmQwMDdjMzFkMjhiMWM4YTgiLCJpYXQiOjE2MzQzMTE4ODYsImV4cCI6MTYzNDkxNjY4Nn0.q6LBCDN1T2PxewPjXkoQ3M9NJuc9GFycC3S0iPKBjNU"
}


### Add new role
POST  http://localhost:3504/role
content-type: application/json

{
    "name":"Manager",
    "color":"F56F6F"
}

# {
#     "name":"Seller",
#     "color":"F5EF55"
# }

# {
#     "name":"Accountant",
#     "color":"55F565"
# }

# {
#     "name":"Warehouse",
#     "color":"4B92FD"
# }

### Get all role
GET http://localhost:3504/role